Bio.create!(name: 'Lodewicus Adriaans',
						info: 'Pretoria',
						body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus accumsan, odio ut tincidunt interdum, lacus lacus interdum ipsum, in facilisis orci ligula ut tortor. Fusce ultricies blandit diam id tristique. Nulla facilisi. Aenean eu convallis mi, nec tristique ligula. Aenean sed mauris imperdiet, tristique turpis nec, laoreet lorem. Ut porttitor, elit vel vulputate accumsan, eros risus porttitor velit, quis molestie lectus mi quis lorem. Pellentesque rutrum bibendum cursus. Integer ut lectus scelerisque, lobortis neque at, ornare enim. Nulla luctus molestie felis, sed scelerisque nunc pulvinar quis. Morbi finibus vel mauris nec tristique.

Aliquam vitae est posuere, tincidunt lectus vel, ullamcorper magna. Cras venenatis orci quis velit rutrum, vitae bibendum ante dignissim. Sed aliquet diam vel tempus feugiat. Pellentesque hendrerit sed leo et consequat. Etiam ac enim vehicula, venenatis neque non, condimentum massa. Nullam eleifend risus nec egestas ultrices. Praesent vel leo sed dolor varius congue et nec felis. Maecenas commodo et nunc faucibus accumsan.

Nam rhoncus sit amet lacus ac tristique. Praesent eu volutpat diam. Cras hendrerit elit quis maximus tincidunt. Aliquam id finibus leo, eget sodales tellus. Curabitur maximus quis magna nec tempus. Nulla eget velit sit amet eros facilisis dapibus ac vel eros. Integer egestas hendrerit sollicitudin. Donec non congue nisl. Donec lacinia eget justo eu condimentum. Vivamus vel nunc a justo pharetra ullamcorper non ullamcorper dui. Suspendisse leo neque, sodales quis orci at, pulvinar sagittis quam. Maecenas quis ultrices erat. Phasellus sed lacus dui. Vestibulum dignissim eros sit amet ipsum sodales, et mattis nulla facilisis. Maecenas vehicula augue aliquam metus semper volutpat. Quisque at nunc leo.

Cras a viverra leo, sit amet scelerisque dolor. Pellentesque porttitor ex quis consequat imperdiet. Sed turpis urna, molestie ac gravida eleifend, pharetra eget tortor. Phasellus vel dapibus mauris, at dapibus libero. Aliquam mattis enim vel egestas rhoncus. Proin semper sapien vitae turpis accumsan varius. Cras aliquam tempor risus in volutpat. Phasellus ac nulla egestas, ullamcorper ligula in, fermentum ex.

In fermentum neque orci, eu elementum tellus eleifend id. Sed faucibus non arcu et lobortis. Phasellus sed ligula porta, tristique enim nec, tincidunt metus. Nam quis venenatis mi. Sed porttitor dapibus viverra. Donec tincidunt, risus pharetra eleifend faucibus, eros lacus semper purus, in dignissim justo mauris id nisl. Morbi tincidunt sem id tortor varius, eu lacinia sapien blandit. Sed quis pulvinar leo. Cras tempus sapien sed pulvinar pharetra. Proin vitae lorem egestas, dapibus dui in, tristique ligula.

Integer tincidunt pretium convallis. Proin nec magna sem. Morbi dictum velit a vehicula faucibus. In hac habitasse platea dictumst. Proin ut tortor eget tortor tempor blandit non eu felis. Fusce elementum mattis erat ut volutpat. Maecenas nec suscipit velit, eget tincidunt mauris. Curabitur eget nisi et magna aliquam commodo. Cras vitae justo quis purus dictum porttitor ac sit amet leo. Etiam tempor turpis quis orci scelerisque mollis.

Nulla lacinia efficitur aliquam. Nunc erat libero, pharetra sed rutrum non, facilisis et mi. Maecenas massa lectus, luctus non aliquet et, iaculis vel magna. Donec erat leo, semper a pulvinar id, gravida ac orci. Vestibulum ut est efficitur, rutrum lacus vel, ultrices massa. Vivamus commodo massa mi, eget tincidunt est commodo in. Sed feugiat metus convallis augue faucibus, quis porttitor nibh bibendum. Nunc sed odio vitae enim pulvinar blandit. Vestibulum tristique pharetra sapien, sagittis hendrerit elit dignissim vitae. Mauris nec tellus vitae magna imperdiet dapibus. Curabitur quis erat at urna luctus fermentum. Quisque fringilla varius vehicula. Phasellus hendrerit bibendum quam at ultricies.

Morbi placerat erat quis imperdiet ultrices. Curabitur ullamcorper neque at neque faucibus ullamcorper. Sed sem purus, sodales eu risus a, molestie posuere ligula. Nulla nec tellus eleifend, finibus justo non, auctor velit. Ut hendrerit lorem sed quam egestas, feugiat fringilla dui porttitor. Pellentesque nec egestas felis. Vivamus ut lacus iaculis, rutrum odio dapibus, iaculis turpis. Morbi elit lorem, interdum sit amet tincidunt et, hendrerit ac nulla. Nullam non lacus commodo, mollis sem sed, iaculis justo. Praesent vulputate semper elit, vitae convallis est rutrum quis. Nunc eget mauris mollis, viverra nulla sed, consequat lectus.

Sed nulla sapien, aliquet quis tincidunt at, imperdiet ut mi. Vivamus volutpat pellentesque ante nec viverra. Quisque neque sapien, cursus vitae convallis sed, commodo in tortor. Vivamus sodales urna eu accumsan congue. Proin vel blandit enim. Pellentesque ac elit neque. Integer mattis mi sed ipsum bibendum condimentum. Vestibulum condimentum est at massa gravida vehicula.

Curabitur a dolor at est scelerisque hendrerit et sed justo. Suspendisse pretium risus sit amet ornare auctor. Quisque a porta risus, eu sodales enim. Mauris id ipsum in sapien volutpat dignissim ac pretium ex. Nulla facilisi. Quisque sodales eu mauris vel condimentum. Praesent nisl sem, rhoncus sed lobortis lacinia, malesuada quis enim. Morbi enim ex, suscipit et dolor vel, fringilla finibus neque. Nulla condimentum dictum feugiat. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer tempus gravida porttitor. Phasellus enim orci, cursus sed sem at, convallis ultrices sapien. Etiam bibendum ex arcu, ut luctus tortor vulputate a. Phasellus egestas nibh nec metus dapibus, id interdum libero volutpat.

Proin nec suscipit felis. Aliquam erat volutpat. Donec in consequat erat, id tempor nisi. Phasellus libero nunc, scelerisque non urna quis, congue pulvinar eros. Nullam consequat scelerisque ex, eget suscipit diam luctus posuere. Quisque tempor pellentesque luctus. Fusce tempor eros in turpis pharetra, eget placerat est finibus.

Nam odio nunc, rutrum quis molestie at, imperdiet in justo. Quisque turpis leo, consectetur convallis risus a, ultricies volutpat neque. Quisque ante dolor, ultrices non faucibus laoreet, porttitor et tellus. Etiam pharetra leo quis turpis dictum feugiat. Aliquam viverra metus vitae leo pretium condimentum. Cras sed diam sem. Aenean volutpat mi lacus. Aliquam fringilla pellentesque diam non bibendum. Ut semper sem enim, vel varius diam tempor quis. Quisque non placerat nisl, quis ornare augue. Sed ac vehicula lorem. In malesuada tellus leo, ut elementum felis elementum ac.

Suspendisse fermentum pellentesque accumsan. Vestibulum finibus accumsan mauris, a finibus nisi aliquet eu. Suspendisse aliquam, nibh eget gravida dignissim, ante lectus porta lectus, sit amet blandit neque ex ac nunc. Etiam vehicula ornare tortor a placerat. Donec vel dui vel nisl consequat commodo viverra')


